import { jsPDF } from 'jspdf';
import logoBlue from '@/assets/logos/logo-blue.png';
import { format, parseISO } from 'date-fns';

export interface PdfCallRow {
  call_date: string | null;
  call_time: string | null;
  caller_name: string | null;
  caller_phone: string | null;
  agent_name: string | null;
  disposition: string | null;
  handle_time_seconds: number | null;
  status: string | null;
}

export interface PdfSummary {
  total_calls: number;
  total_minutes: number;
  missed_calls: number;
  avg_handle_seconds: number;
}

const CFG = {
  pw: 210,
  ph: 297,
  ml: 15,
  mr: 15,
  mt: 26,
  mb: 18,
  c: {
    primary:   '#005FB4',
    headerBg:  '#1e3a5f',
    text:      '#1e293b',
    muted:     '#64748b',
    lightBg:   '#f8fafc',
    rowAlt:    '#f1f5f9',
    border:    '#e2e8f0',
  },
};

const hex = (h: string): [number, number, number] => {
  const r = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(h);
  return r ? [parseInt(r[1], 16), parseInt(r[2], 16), parseInt(r[3], 16)] : [0, 0, 0];
};

const loadBase64 = (url: string): Promise<string> =>
  fetch(url)
    .then(r => r.blob())
    .then(b => new Promise<string>((res, rej) => {
      const fr = new FileReader();
      fr.onloadend = () => res(fr.result as string);
      fr.onerror = rej;
      fr.readAsDataURL(b);
    }));

const formatHms = (sec: number | null): string => {
  if (!sec) return '–';
  const m = Math.floor(sec / 60);
  const s = sec % 60;
  return `${m}:${String(s).padStart(2, '0')}`;
};

const drawHeader = (doc: jsPDF, logo: string): void => {
  doc.setFillColor(...hex(CFG.c.primary));
  doc.rect(0, 0, CFG.pw, 6, 'F');
  doc.addImage(logo, 'PNG', CFG.ml, 9, 28, 7);
  doc.setFontSize(9);
  doc.setTextColor(...hex(CFG.c.muted));
  doc.setFont('helvetica', 'normal');
  doc.text('Call Report', CFG.pw - CFG.mr, 14, { align: 'right' });
  doc.setDrawColor(...hex(CFG.c.primary));
  doc.setLineWidth(0.4);
  doc.line(CFG.ml, 19, CFG.pw - CFG.mr, 19);
};

const drawFooter = (doc: jsPDF, page: number, total: number, generated: string): void => {
  const fy = CFG.ph - 7;
  doc.setDrawColor(...hex(CFG.c.border));
  doc.setLineWidth(0.3);
  doc.line(CFG.ml, fy - 4, CFG.pw - CFG.mr, fy - 4);
  doc.setFontSize(8);
  doc.setTextColor(...hex(CFG.c.muted));
  doc.setFont('helvetica', 'normal');
  doc.text(`Page ${page} of ${total}`, CFG.ml, fy);
  doc.text(`Generated by 24H Virtual · ${generated}`, CFG.pw - CFG.mr, fy, { align: 'right' });
};

// Table column definitions — total 180mm = pw - ml - mr
const COLS = [
  { label: 'Date',        w: 22 },
  { label: 'Time',        w: 18 },
  { label: 'Caller',      w: 35 },
  { label: 'Agent',       w: 30 },
  { label: 'Disposition', w: 28 },
  { label: 'Duration',    w: 20 },
  { label: 'Status',      w: 27 },
];

const HEADER_H = 8;
const ROW_H    = 6.5;

const drawTableHeader = (doc: jsPDF, y: number): number => {
  const cw = CFG.pw - CFG.ml - CFG.mr;
  doc.setFillColor(...hex(CFG.c.headerBg));
  doc.rect(CFG.ml, y, cw, HEADER_H, 'F');
  let x = CFG.ml;
  COLS.forEach(c => {
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text(c.label, x + 2, y + 5.5);
    x += c.w;
  });
  return y + HEADER_H;
};

const drawTableRow = (doc: jsPDF, row: PdfCallRow, y: number, alt: boolean): number => {
  const cw = CFG.pw - CFG.ml - CFG.mr;
  if (alt) {
    doc.setFillColor(...hex(CFG.c.rowAlt));
    doc.rect(CFG.ml, y, cw, ROW_H, 'F');
  }
  doc.setDrawColor(...hex(CFG.c.border));
  doc.setLineWidth(0.2);
  doc.line(CFG.ml, y + ROW_H, CFG.ml + cw, y + ROW_H);

  const dateStr = row.call_date
    ? (() => { try { return format(parseISO(row.call_date!), 'M/d/yy'); } catch { return row.call_date!; } })()
    : '–';

  const cells = [
    dateStr,
    row.call_time ?? '–',
    row.caller_name || row.caller_phone || '–',
    row.agent_name || '–',
    row.disposition || '–',
    formatHms(row.handle_time_seconds),
    row.status || '–',
  ];

  doc.setFontSize(8);
  doc.setTextColor(...hex(CFG.c.text));
  doc.setFont('helvetica', 'normal');

  let x = CFG.ml;
  cells.forEach((cell, i) => {
    const maxW = COLS[i].w - 3;
    const lines = doc.splitTextToSize(String(cell), maxW);
    doc.text(lines[0] ?? '', x + 2, y + 4.5);
    x += COLS[i].w;
  });

  return y + ROW_H;
};

export async function downloadCallReportPdf(
  calls: PdfCallRow[],
  summary: PdfSummary | null,
  clientName: string,
  period: string
): Promise<void> {
  const logo      = await loadBase64(logoBlue);
  const generated = format(new Date(), 'MMM d, yyyy');
  const periodLabel = (() => {
    try { return format(parseISO(`${period}-01`), 'MMMM yyyy'); } catch { return period; }
  })();

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const cw  = CFG.pw - CFG.ml - CFG.mr; // 180mm

  // ── Page 1: header + title block + summary stats ───────────────────
  drawHeader(doc, logo);

  let y = CFG.mt;

  doc.setFontSize(18);
  doc.setTextColor(...hex(CFG.c.text));
  doc.setFont('helvetica', 'bold');
  doc.text('Call Report', CFG.ml, y);
  y += 7;

  doc.setFontSize(11);
  doc.setTextColor(...hex(CFG.c.muted));
  doc.setFont('helvetica', 'normal');
  doc.text(`${clientName}  ·  ${periodLabel}`, CFG.ml, y);
  y += 10;

  // Summary stat boxes
  const stats = [
    { label: 'Total Calls',     value: String(summary?.total_calls ?? 0) },
    { label: 'Total Minutes',   value: summary?.total_minutes != null ? Number(summary.total_minutes).toFixed(0) : '0' },
    { label: 'Missed Calls',    value: String(summary?.missed_calls ?? 0) },
    { label: 'Avg Handle Time', value: formatHms(summary?.avg_handle_seconds ? Math.round(summary.avg_handle_seconds) : null) },
  ];
  const boxW = (cw - 9) / 4;
  const boxH = 22;
  stats.forEach((s, i) => {
    const bx = CFG.ml + i * (boxW + 3);
    doc.setFillColor(...hex(CFG.c.lightBg));
    doc.setDrawColor(...hex(CFG.c.border));
    doc.setLineWidth(0.3);
    doc.roundedRect(bx, y, boxW, boxH, 2, 2, 'FD');
    doc.setFontSize(15);
    doc.setTextColor(...hex(CFG.c.primary));
    doc.setFont('helvetica', 'bold');
    doc.text(s.value, bx + boxW / 2, y + 11, { align: 'center' });
    doc.setFontSize(7.5);
    doc.setTextColor(...hex(CFG.c.muted));
    doc.setFont('helvetica', 'normal');
    doc.text(s.label, bx + boxW / 2, y + 18, { align: 'center' });
  });
  y += boxH + 8;

  // ── Call log table ─────────────────────────────────────────────────
  y = drawTableHeader(doc, y);

  const maxY = CFG.ph - CFG.mb - ROW_H;

  for (let i = 0; i < calls.length; i++) {
    if (y + ROW_H > maxY) {
      doc.addPage();
      drawHeader(doc, logo);
      y = CFG.mt;
      y = drawTableHeader(doc, y);
    }
    y = drawTableRow(doc, calls[i], y, i % 2 === 1);
  }

  if (calls.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(...hex(CFG.c.muted));
    doc.text('No call records for this period.', CFG.ml, y + 8);
  }

  // ── Footers (post-pass so total page count is known) ──────────────
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    drawFooter(doc, p, total, generated);
  }

  const safe = clientName.replace(/[^a-z0-9-_]/gi, '-');
  doc.save(`call-report-${safe}-${period}.pdf`);
}
