/**
 * Product Testing Segment Registry
 *
 * Single source of truth for the Superadmin Product Testing launcher.
 * Each segment maps to a real route in the app. Segments are NEVER cloned
 * or faked: launching a segment opens its real route with `?testSegment=<id>`,
 * and the TestModeBanner overlays trace metadata.
 *
 * To add a new testable surface, add an entry here. Keep `route` canonical
 * (the same path used in the actual route registration).
 */

export type SegmentCategory = 'dashboard' | 'onboarding' | 'product' | 'diagnostic';

export type SegmentStatus =
  | 'production'        // fully wired, safe to test against live data
  | 'sandbox'           // safe internal test surface
  | 'partial'           // works but missing pieces
  | 'placeholder'       // route exists but content is stubbed
  | 'requires-context'; // needs seeded data (campaign, partner, etc.)

export type SegmentRequirement =
  | 'admin-role'
  | 'client-role'
  | 'agent-role'
  | 'supervisor-role'
  | 'sales-role'
  | 'billing-role'
  | 'tech-role'
  | 'hr-role'
  | 'white-label-role'
  | 'wl-client-role'
  | 'affiliate-role'
  | 'partner-slug'
  | 'partner-id'
  | 'client-id'
  | 'campaign-id'
  | 'live-campaign'
  | 'lead-id'
  | 'ticket-id';

export interface ProductTestingSegment {
  id: string;
  label: string;
  category: SegmentCategory;
  description: string;
  /** Canonical route. May contain :paramName placeholders, in which case `requires` should reflect that. */
  route: string;
  /** Persona this segment represents (for role-mismatch detection). */
  role:
    | 'public'
    | 'admin'
    | 'client'
    | 'agent'
    | 'supervisor'
    | 'sales'
    | 'billing'
    | 'tech'
    | 'hr'
    | 'white_label'
    | 'wl_client'
    | 'affiliate';
  productArea: string;
  status: SegmentStatus;
  supportsNewTab: boolean;
  supportsTrace: boolean;
  supportsSmokeTest: boolean;
  requires: SegmentRequirement[];
  notes?: string;
}

export const PRODUCT_TESTING_SEGMENTS: ProductTestingSegment[] = [
  // ============================================================
  // DASHBOARD SEGMENTS
  // ============================================================
  {
    id: 'website',
    label: 'Public Website',
    category: 'dashboard',
    description: 'Marketing site home (Index page) as seen by anonymous visitors.',
    route: '/',
    role: 'public',
    productArea: 'Marketing',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: [],
  },
  {
    id: 'superadmin-dashboard',
    label: 'Superadmin Dashboard',
    category: 'dashboard',
    description: 'Top-level admin overview (the Superadmin landing).',
    route: '/admin',
    role: 'admin',
    productArea: 'Admin',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'admin-dashboard',
    label: 'Admin Overview',
    category: 'dashboard',
    description: 'Admin Overview page with KPIs and pipeline summary.',
    route: '/admin',
    role: 'admin',
    productArea: 'Admin',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'supervisor-dashboard',
    label: 'Supervisor Dashboard',
    category: 'dashboard',
    description: 'Supervisor team oversight and SLA monitoring surface.',
    route: '/staff/supervisor',
    role: 'supervisor',
    productArea: 'Operations',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['supervisor-role'],
  },
  {
    id: 'agent-dashboard',
    label: 'Agent Dashboard',
    category: 'dashboard',
    description: 'Frontline agent workspace.',
    route: '/staff/agent',
    role: 'agent',
    productArea: 'Operations',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['agent-role'],
  },
  {
    id: 'sales-dashboard',
    label: 'Sales Dashboard',
    category: 'dashboard',
    description: 'Sales pipeline, leads, and conversion tracking.',
    route: '/staff/sales',
    role: 'sales',
    productArea: 'Sales',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['sales-role'],
  },
  {
    id: 'billing-dashboard',
    label: 'Billing Dashboard',
    category: 'dashboard',
    description: 'Billing, payouts, and subscription operations.',
    route: '/staff/billing',
    role: 'billing',
    productArea: 'Billing',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['billing-role'],
  },
  {
    id: 'tech-dashboard',
    label: 'Tech Support Dashboard',
    category: 'dashboard',
    description: 'Technical issue tracking and chat deployments.',
    route: '/staff/tech',
    role: 'tech',
    productArea: 'Tech',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['tech-role'],
  },
  {
    id: 'hr-dashboard',
    label: 'HR Portal',
    category: 'dashboard',
    description: 'HR lifecycle hub: directory, payroll, time off, jobs.',
    route: '/hr-portal',
    role: 'hr',
    productArea: 'HR',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['hr-role'],
  },
  {
    id: 'client-dashboard',
    label: 'Client Dashboard',
    category: 'dashboard',
    description: 'End-customer dashboard: calls, scripts, billing, settings.',
    route: '/client-dashboard',
    role: 'client',
    productArea: 'Client',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['client-role'],
  },
  {
    id: 'wl-partner-dashboard',
    label: 'WL Partner Dashboard',
    category: 'dashboard',
    description: 'White-Label partner control center.',
    route: '/white-label-dashboard',
    role: 'white_label',
    productArea: 'White Label',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['white-label-role'],
  },
  {
    id: 'wl-end-client-portal',
    label: 'WL End-Client Portal',
    category: 'dashboard',
    description: 'Partner-branded end-client portal (masked /portal/:slug/*).',
    route: '/portal/:slug',
    role: 'wl_client',
    productArea: 'White Label',
    status: 'requires-context',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: false,
    requires: ['partner-slug', 'wl-client-role'],
    notes: 'Replace :slug with a real partner slug to launch this segment.',
  },
  {
    id: 'affiliate-dashboard',
    label: 'Affiliate Dashboard',
    category: 'dashboard',
    description: 'Affiliate referral tracking and commissions.',
    route: '/affiliate',
    role: 'affiliate',
    productArea: 'Affiliate',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['affiliate-role'],
  },

  // ============================================================
  // ONBOARDING SEGMENTS
  // ============================================================
  {
    id: 'get-started-wizard',
    label: 'Get Started Wizard (Public)',
    category: 'onboarding',
    description: '6-step public onboarding flow with personalized recommendations.',
    route: '/get-started',
    role: 'public',
    productArea: 'Onboarding',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: [],
  },
  {
    id: 'client-onboarding',
    label: 'Client Onboarding',
    category: 'onboarding',
    description: 'Authenticated client first-run onboarding inside the dashboard.',
    route: '/client-dashboard',
    role: 'client',
    productArea: 'Onboarding',
    status: 'partial',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: false,
    requires: ['client-role'],
    notes: 'AI Onboarding Assistant triggers on first login for client accounts.',
  },
  {
    id: 'agent-onboarding',
    label: 'Agent Onboarding',
    category: 'onboarding',
    description: 'Agent training, profile setup, and shift readiness.',
    route: '/staff/agent/onboarding',
    role: 'agent',
    productArea: 'Onboarding',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['agent-role'],
  },
  {
    id: 'wl-partner-onboarding',
    label: 'WL Partner Onboarding',
    category: 'onboarding',
    description: 'White-Label partner activation flow.',
    route: '/white-label-dashboard',
    role: 'white_label',
    productArea: 'Onboarding',
    status: 'partial',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: false,
    requires: ['white-label-role'],
    notes: 'Onboarding shown inline on partner dashboard until checklist completion.',
  },
  {
    id: 'launch-checklist',
    label: 'Launch Checklist',
    category: 'onboarding',
    description: 'Admin pre-launch readiness checklist.',
    route: '/admin/launch-checklist',
    role: 'admin',
    productArea: 'Onboarding',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'fulfillment-intake',
    label: 'Fulfillment Intake',
    category: 'onboarding',
    description: 'Admin fulfillment intake queue for new client setup.',
    route: '/admin/fulfillment-intake',
    role: 'admin',
    productArea: 'Onboarding',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },

  // ============================================================
  // PRODUCT / SOLUTION SEGMENTS
  // ============================================================
  {
    id: 'campaigns',
    label: 'Campaigns',
    category: 'product',
    description: 'Campaign OS overview and management.',
    route: '/admin/campaign-os/campaigns',
    role: 'admin',
    productArea: 'Campaign OS',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'crm-leads',
    label: 'CRM / Leads',
    category: 'product',
    description: 'Admin lead pipeline and CRM workspace.',
    route: '/admin/leads',
    role: 'admin',
    productArea: 'CRM',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'active-accounts',
    label: 'Active Accounts',
    category: 'product',
    description: 'Active client accounts (Campaign OS Clients view).',
    route: '/admin/campaign-os/clients',
    role: 'admin',
    productArea: 'Campaign OS',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'wl-partners',
    label: 'WL Partners',
    category: 'product',
    description: 'White-Label partner directory.',
    route: '/admin/partners',
    role: 'admin',
    productArea: 'White Label',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'reporting',
    label: 'Reporting',
    category: 'product',
    description: 'Campaign OS reporting and analytics.',
    route: '/admin/campaign-os/reporting',
    role: 'admin',
    productArea: 'Reporting',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'templates',
    label: 'Templates',
    category: 'product',
    description: 'Campaign templates library.',
    route: '/admin/campaign-os/templates',
    role: 'admin',
    productArea: 'Campaign OS',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'drafts',
    label: 'Drafts Review',
    category: 'product',
    description: 'Campaign drafts pending approval.',
    route: '/admin/campaign-os/drafts',
    role: 'admin',
    productArea: 'Campaign OS',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'five9-runtime',
    label: 'Five9 Runtime (Iframe Script)',
    category: 'product',
    description: 'Chromeless campaign script runtime served to Five9 iframe.',
    route: '/run/campaign/:campaignId/script',
    role: 'agent',
    productArea: 'Runtime',
    status: 'requires-context',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: false,
    requires: ['campaign-id', 'live-campaign'],
    notes: 'Replace :campaignId with a real published campaign id.',
  },
  {
    id: 'script-builder',
    label: 'Script Builder',
    category: 'product',
    description: 'Campaign script tree authoring.',
    route: '/admin/campaign-os/campaigns',
    role: 'admin',
    productArea: 'Campaign OS',
    status: 'requires-context',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: false,
    requires: ['admin-role', 'campaign-id'],
    notes: 'Open a campaign, then click Script Builder. Direct route is /admin/campaign-os/campaigns/:id/script.',
  },
  {
    id: 'training',
    label: 'Training & Signoffs',
    category: 'product',
    description: 'Supervisor training signoffs and quiz review queue.',
    route: '/staff/supervisor/training-signoffs',
    role: 'supervisor',
    productArea: 'Training',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['supervisor-role'],
  },
  {
    id: 'support-tickets',
    label: 'Support Tickets',
    category: 'product',
    description: 'Admin ticket queue across all departments.',
    route: '/admin/tickets',
    role: 'admin',
    productArea: 'Support',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'billing',
    label: 'Billing & Subscriptions',
    category: 'product',
    description: 'Admin billing and subscription operations.',
    route: '/admin/billing',
    role: 'admin',
    productArea: 'Billing',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'payouts',
    label: 'Payouts (Billing)',
    category: 'product',
    description: 'Billing payouts queue (Airwallex).',
    route: '/staff/billing/payouts',
    role: 'billing',
    productArea: 'Billing',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['billing-role'],
  },
  {
    id: 'growth-hub',
    label: 'Growth Hub',
    category: 'product',
    description: 'Marketing engine: blog, email, social, newsletter.',
    route: '/admin/growth-hub',
    role: 'admin',
    productArea: 'Growth',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'discoverability',
    label: 'Discoverability (SEO/AEO/GEO)',
    category: 'product',
    description: 'DB-backed SEO/AEO/GEO content operations.',
    route: '/admin/discoverability',
    role: 'admin',
    productArea: 'Growth',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'mission-control',
    label: 'Mission Control',
    category: 'product',
    description: 'Centralized governance UI for AI backend agents.',
    route: '/admin/mission-control',
    role: 'admin',
    productArea: 'AI Ops',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'outline',
    label: 'Build Outline',
    category: 'product',
    description: 'Source of build truth: phases, waves, items.',
    route: '/outline',
    role: 'admin',
    productArea: 'Platform',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: [],
  },
  {
    id: 'launch-controls',
    label: 'Launch Controls',
    category: 'product',
    description: 'Phase/wave gate overrides and launch flag control.',
    route: '/admin/launch-controls',
    role: 'admin',
    productArea: 'Platform',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'wl-branding',
    label: 'WL Branding & Domains',
    category: 'product',
    description: 'White-Label branding, hostname, and config diff health.',
    route: '/admin/wl-health',
    role: 'admin',
    productArea: 'White Label',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'wl-preview',
    label: 'WL Partner Preview',
    category: 'product',
    description: 'Live preview of a partner-branded portal as the partner.',
    route: '/admin/wl-preview/:partnerId',
    role: 'admin',
    productArea: 'White Label',
    status: 'requires-context',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: false,
    requires: ['admin-role', 'partner-id'],
    notes: 'Replace :partnerId with a real partner UUID.',
  },

  // ============================================================
  // DIAGNOSTIC / UTILITY SEGMENTS
  // ============================================================
  {
    id: 'audit-log',
    label: 'Audit Log',
    category: 'diagnostic',
    description: 'Cross-cutting admin audit log of sensitive actions.',
    route: '/admin/audit-log',
    role: 'admin',
    productArea: 'Diagnostics',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'dashboard-events',
    label: 'Dashboard Analytics Events',
    category: 'diagnostic',
    description: 'Per-button/per-tab dashboard event explorer.',
    route: '/admin/analytics/dashboard-events',
    role: 'admin',
    productArea: 'Diagnostics',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'wl-leak-audit',
    label: 'WL Leak Audit',
    category: 'diagnostic',
    description: 'Detects cross-tenant data leakage in WL surfaces.',
    route: '/admin/wl-leak-audit',
    role: 'admin',
    productArea: 'Diagnostics',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'wl-config-diff',
    label: 'WL Config Diff',
    category: 'diagnostic',
    description: 'Diff partner config against canonical baseline.',
    route: '/admin/wl-config-diff',
    role: 'admin',
    productArea: 'Diagnostics',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'email-preview',
    label: 'Email Template Preview',
    category: 'diagnostic',
    description: 'Render and inspect transactional email templates.',
    route: '/admin/email-preview',
    role: 'admin',
    productArea: 'Diagnostics',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
  {
    id: 'architecture',
    label: 'System Architecture',
    category: 'diagnostic',
    description: 'High-level system architecture map.',
    route: '/admin/architecture',
    role: 'admin',
    productArea: 'Diagnostics',
    status: 'production',
    supportsNewTab: true,
    supportsTrace: true,
    supportsSmokeTest: true,
    requires: ['admin-role'],
  },
];

export function getSegmentById(id: string | null | undefined): ProductTestingSegment | null {
  if (!id) return null;
  return PRODUCT_TESTING_SEGMENTS.find((s) => s.id === id) ?? null;
}

export const SEGMENT_CATEGORY_LABELS: Record<SegmentCategory, string> = {
  dashboard: 'Dashboard Segments',
  onboarding: 'Onboarding Segments',
  product: 'Product / Solution Segments',
  diagnostic: 'Diagnostic / Utility Segments',
};

export const SEGMENT_STATUS_LABELS: Record<SegmentStatus, string> = {
  production: 'Production',
  sandbox: 'Sandbox',
  partial: 'Partial',
  placeholder: 'Placeholder',
  'requires-context': 'Requires Context',
};
