
-- Create a function that seeds Resend KB articles for a given partner
CREATE OR REPLACE FUNCTION public.seed_resend_kb_articles(p_partner_id uuid)
RETURNS void AS $$
BEGIN
  INSERT INTO public.wl_knowledge_base (partner_id, title, content, category, tags, content_type, audience, sort_order)
  VALUES
  -- Article 1: Overview
  (p_partner_id, 'Resend Email Integration Overview',
  E'# Resend Email Integration Overview\n\nResend is a modern email delivery platform that lets you send professional emails to your clients directly from the Growth Hub.\n\n## Why Connect Resend?\n\nWith Resend connected, you can:\n\n- **Send newsletters** to your client list with one click\n- **Track delivery status** of every email sent\n- **Manage contacts** — build and maintain your client email list\n- **Use your own domain** — emails come from your business, not ours\n\n## What You''ll Need\n\n1. A **Resend account** (free tier available at [resend.com](https://resend.com))\n2. A **verified sender email** or domain in Resend\n3. Your **Resend API key**\n\n## How It Works\n\n1. Sign up for Resend and get your API key\n2. Verify your sender email address or domain\n3. Connect your Resend account in Growth Hub > Email Integration\n4. Add your client contacts\n5. Generate newsletters and send them directly!\n\n## Related Articles\n\n- How to Sign Up for Resend\n- How to Get Your Resend API Key\n- How to Verify Your Sender Email in Resend\n- How to Connect Resend to Growth Hub',
  'integrations', ARRAY['resend','email','integration','overview','setup'], 'feature', 'client', 1),

  -- Article 2: Sign Up
  (p_partner_id, 'How to Sign Up for Resend',
  E'# How to Sign Up for Resend\n\nResend is a free email platform that powers the email sending feature in your Growth Hub. Here''s how to create your account.\n\n## Prerequisites\n\n- A valid email address\n- (Optional) Your own business domain name\n\n## Steps\n\n1. Visit [resend.com](https://resend.com) in your browser\n2. Click the **"Get Started"** button\n3. You can sign up with your **GitHub account** or use **email and password**\n4. If using email: enter your email address and create a strong password\n5. Click **"Create Account"**\n6. Check your email inbox for a verification link from Resend\n7. Click the verification link to confirm your account\n8. You''re done! Your Resend account is ready\n\n## Resend Free Tier\n\nResend offers a generous free tier that includes:\n- Up to **100 emails per day**\n- Up to **3,000 emails per month**\n- 1 custom domain\n\nThis is more than enough to get started with client newsletters.\n\n## Next Steps\n\n- Get your Resend API key\n- Verify your sender email address',
  'integrations', ARRAY['resend','email','signup','account','setup'], 'procedure', 'client', 2),

  -- Article 3: API Key
  (p_partner_id, 'How to Get Your Resend API Key',
  E'# How to Get Your Resend API Key\n\nYour API key is what connects your Resend account to the Growth Hub. Think of it as a secure password that lets our system send emails on your behalf.\n\n## Steps\n\n1. Log in to your Resend account at [resend.com](https://resend.com)\n2. In the left sidebar, click **"API Keys"**\n3. Click the **"+ Create API Key"** button\n4. Give your key a name (e.g., "Growth Hub")\n5. For permissions, select **"Sending access"** (this is the safest option)\n6. Optionally restrict to a specific domain if you have one set up\n7. Click **"Add"**\n8. **Important:** Your API key will be displayed once. Copy it immediately!\n9. Store it somewhere safe — you won''t be able to see it again\n\n## Security Tips\n\n- **Never share your API key** with anyone\n- **Don''t post it** in emails, chats, or public forums\n- If you think your key has been compromised, delete it in Resend and create a new one\n- You can create multiple API keys for different purposes\n\n## Next Steps\n\n- Verify your sender email address\n- Connect Resend to Growth Hub',
  'integrations', ARRAY['resend','email','api-key','setup','security'], 'procedure', 'client', 3),

  -- Article 4: Verify Sender
  (p_partner_id, 'How to Verify Your Sender Email in Resend',
  E'# How to Verify Your Sender Email in Resend\n\nBefore you can send emails, Resend needs to verify that you own the email address or domain you want to send from. This prevents spam and ensures your emails are delivered.\n\n## Option 1: Domain Verification (Recommended)\n\nIf you have your own business domain (e.g., yourbusiness.com), this is the best option for professional emails.\n\n1. Log in to [resend.com](https://resend.com)\n2. Click **"Domains"** in the left sidebar\n3. Click **"+ Add Domain"**\n4. Enter your domain name (e.g., yourbusiness.com)\n5. Resend will show you **DNS records** to add\n6. Log in to your domain registrar (GoDaddy, Namecheap, Cloudflare, etc.)\n7. Add the DNS records exactly as shown by Resend\n8. Go back to Resend and click **"Verify"**\n9. Verification can take a few minutes to a few hours\n\n## Option 2: Single Email Verification\n\nIf you don''t have a custom domain, you can verify a single email address. Note: emails will be sent via Resend''s shared domain.\n\n1. When connecting in Growth Hub, simply enter your email address\n2. Resend will use their onboarding@resend.dev domain for initial testing\n3. For production use, domain verification is strongly recommended\n\n## Why Verification Matters\n\n- **Prevents spam** — email providers trust verified senders\n- **Better delivery** — your emails are less likely to land in spam folders\n- **Professional appearance** — emails come from your domain, not a generic one\n- **Required by law** — CAN-SPAM and GDPR require identifiable senders\n\n## Troubleshooting\n\n- DNS changes can take up to 48 hours to propagate\n- Double-check that you copied the DNS records exactly\n- Make sure there are no extra spaces in the records\n- Contact your domain registrar''s support if you need help adding DNS records',
  'integrations', ARRAY['resend','email','domain','verification','dns','setup'], 'procedure', 'client', 4),

  -- Article 5: Connect to Growth Hub
  (p_partner_id, 'How to Connect Resend to Growth Hub',
  E'# How to Connect Resend to Growth Hub\n\nOnce you have your Resend account, API key, and verified sender email, you''re ready to connect everything together.\n\n## Prerequisites\n\n- A Resend account (see: How to Sign Up for Resend)\n- Your Resend API key (see: How to Get Your Resend API Key)\n- A verified sender email or domain (see: How to Verify Your Sender Email)\n\n## Steps\n\n1. Go to **Growth Hub** from your dashboard sidebar\n2. Click on the **"Email Integration"** card\n3. In the **API Key** field, paste your Resend API key\n4. In the **Sender Email** field, enter your verified email address (e.g., hello@yourbusiness.com)\n5. In the **Sender Name** field, enter the display name for your emails (e.g., "Your Business Name")\n6. Click **"Test Connection"**\n7. If successful, you''ll see a green "Connected" status\n8. Your Resend integration is now active!\n\n## What "Test Connection" Does\n\nWhen you click Test Connection, we:\n- Verify your API key is valid\n- Check that your account is active\n- Confirm the connection is working\n\n## After Connecting\n\nYou can now:\n- Add contacts to your email list\n- Send newsletters directly from the Newsletter Generator\n- Track your email send history\n\n## Troubleshooting\n\nSee: Resend Connection Troubleshooting',
  'integrations', ARRAY['resend','email','connect','setup','growth-hub'], 'procedure', 'client', 5),

  -- Article 6: Contact List
  (p_partner_id, 'How to Build Your Email Contact List',
  E'# How to Build Your Email Contact List\n\nBefore you can send newsletters, you need to add the email addresses of the clients you want to reach.\n\n## Adding Contacts Manually\n\n1. Go to **Growth Hub > Email Integration**\n2. Scroll to the **Contacts** section\n3. Click **"Add Contact"**\n4. Enter the contact''s **name** and **email address**\n5. (Optional) Add **tags** to organize contacts (e.g., "VIP", "new-client")\n6. Click **"Save"**\n\n## Importing Contacts via CSV\n\n1. Prepare a CSV file with columns: **name, email**\n2. In the Contacts section, click **"Import CSV"**\n3. Paste your CSV data into the text area\n4. Click **"Import"**\n5. Review the imported contacts\n\n## Managing Contacts\n\n- **Edit**: Click the edit icon next to any contact to update their details\n- **Unsubscribe**: Toggle the subscribed status to mark someone as unsubscribed. They won''t receive future emails.\n- **Tags**: Use tags to create segments (e.g., send newsletters only to "active-clients")\n\n## Best Practices\n\n- **Get permission first** — only add people who have agreed to receive emails from you\n- **Keep your list clean** — remove bounced or invalid emails\n- **Use tags** to organize contacts by type, location, or interest\n- **Respect unsubscribes** — never re-add someone who has opted out\n\n## Legal Requirements\n\n- You must have consent to email your contacts\n- Every email must include a way to unsubscribe\n- Follow CAN-SPAM (US), GDPR (EU), and CASL (Canada) regulations',
  'integrations', ARRAY['resend','email','contacts','import','csv','list'], 'procedure', 'client', 6),

  -- Article 7: Send Newsletter
  (p_partner_id, 'How to Send a Newsletter to Your Clients',
  E'# How to Send a Newsletter to Your Clients\n\nThis guide walks you through the complete process of sending a newsletter from generation to delivery.\n\n## Prerequisites\n\n- Resend connected (see: How to Connect Resend to Growth Hub)\n- At least one contact in your email list\n- A generated newsletter draft\n\n## Step-by-Step\n\n### 1. Generate Your Newsletter\n\n1. Go to **Growth Hub > Newsletter Generator**\n2. Select the **month** you want to create a newsletter for\n3. Click **"Generate Newsletter"**\n4. The AI will create a newsletter from your recent blog posts\n\n### 2. Review the Content\n\n1. Read through the generated **subject line** — this is what recipients see in their inbox\n2. Preview the **email content** in the preview pane\n3. Make sure all blog post links and information look correct\n\n### 3. Send the Newsletter\n\n1. Click the **"Send via Email"** button\n2. Choose which contacts to send to (all subscribed contacts by default)\n3. Confirm the send\n4. The system will send the email using your connected Resend account\n\n### 4. Track Delivery\n\n1. Go to **Growth Hub > Email Integration**\n2. Check the **Send History** section\n3. You''ll see the status of each send: total recipients, successful sends, and any failures\n\n## Tips\n\n- **Send a test first** — send to yourself before blasting your full list\n- **Check your subject line** — a good subject line improves open rates\n- **Don''t send too often** — monthly newsletters work best for most businesses\n- **Review content** — always proofread before sending',
  'email', ARRAY['resend','email','newsletter','send','delivery'], 'procedure', 'client', 7),

  -- Article 8: Troubleshooting
  (p_partner_id, 'Resend Connection Troubleshooting',
  E'# Resend Connection Troubleshooting\n\nHaving trouble connecting or sending emails? Here are solutions to the most common issues.\n\n## "Connection test failed"\n\n**Possible causes:**\n- Your API key may be incorrect or expired\n- Your Resend account may be inactive\n\n**Solutions:**\n1. Log in to [resend.com](https://resend.com) and verify your account is active\n2. Go to API Keys and check that your key hasn''t been deleted\n3. Try creating a new API key and re-entering it\n\n## "API key invalid"\n\n**Possible causes:**\n- The API key was copied incorrectly (extra spaces, missing characters)\n- The API key was deleted from your Resend account\n\n**Solutions:**\n1. In Resend, go to API Keys\n2. Delete the old key and create a new one\n3. Copy the new key carefully (use Ctrl+C / Cmd+C)\n4. Paste it into the Growth Hub Email Integration page\n\n## "Sender email not verified"\n\n**Possible causes:**\n- Your sender email/domain hasn''t been verified in Resend\n- DNS records haven''t propagated yet\n\n**Solutions:**\n1. Log in to Resend and check your Domains page\n2. Make sure your domain shows as "Verified"\n3. If pending, wait up to 48 hours for DNS propagation\n4. See: How to Verify Your Sender Email in Resend\n\n## "Send failed"\n\n**Possible causes:**\n- You''ve exceeded your daily sending limit\n- The recipient email address is invalid\n- Your Resend account has been suspended\n\n**Solutions:**\n1. Check your Resend dashboard for any account alerts\n2. Verify recipient email addresses are valid\n3. Check if you''ve hit your daily limit (100/day on free tier)\n4. Try again later or upgrade your Resend plan\n\n## Still Need Help?\n\n- **Resend support**: Visit [resend.com/docs](https://resend.com/docs) for their official documentation\n- **Contact us**: Reach out through the Support page in your dashboard and we''ll help you troubleshoot',
  'integrations', ARRAY['resend','email','troubleshooting','errors','help'], 'feature', 'client', 8),

  -- Article 9: Best Practices
  (p_partner_id, 'Email Deliverability Best Practices',
  E'# Email Deliverability Best Practices\n\nFollow these tips to make sure your newsletters reach your clients'' inboxes and not their spam folders.\n\n## 1. Verify Your Sender Domain\n\nAlways verify your business domain in Resend rather than using a free email address. Emails from verified domains are trusted by email providers.\n\n## 2. Use a Professional Sender Name\n\nUse your business name as the sender (e.g., "Smith Consulting") rather than a personal name or generic text. This builds recognition and trust.\n\n## 3. Keep Your Contact List Clean\n\n- Remove email addresses that consistently bounce\n- Remove inactive contacts who never open your emails\n- Never buy email lists — these lead to high spam rates\n\n## 4. Write Clear Subject Lines\n\n- Keep subject lines under 50 characters when possible\n- Be specific about the content (e.g., "January Marketing Update" not "Newsletter")\n- Avoid ALL CAPS and excessive punctuation (!!!)\n- Don''t use misleading subject lines\n\n## 5. Avoid Spam Trigger Words\n\nCertain words can trigger spam filters. Avoid:\n- "Free", "Act now", "Limited time"\n- "Click here", "Buy now", "Order today"\n- Excessive use of "$" or "%" symbols\n\n## 6. Follow the Law\n\n**CAN-SPAM (United States):**\n- Include your physical business address\n- Provide a clear way to unsubscribe\n- Honor unsubscribe requests within 10 business days\n\n**GDPR (European Union):**\n- Get explicit consent before emailing\n- Allow contacts to withdraw consent easily\n- Be transparent about how you use their data\n\n**CASL (Canada):**\n- Get express or implied consent\n- Include sender identification\n- Provide an unsubscribe mechanism\n\n## 7. Monitor Your Delivery Status\n\nAfter each send, check the Email Integration page for:\n- **Successful sends** — emails that were accepted for delivery\n- **Failed sends** — emails that bounced or were rejected\n- If you see high failure rates, clean your contact list\n\n## 8. Send Consistently\n\n- Pick a regular schedule (monthly works well)\n- Don''t send too frequently (weekly can feel like spam)\n- Don''t go months without sending (contacts forget who you are)',
  'email', ARRAY['resend','email','deliverability','best-practices','spam','compliance'], 'feature', 'client', 9)

  ON CONFLICT DO NOTHING;
END;
$$ LANGUAGE plpgsql;

-- Seed articles for all existing partners
DO $$
DECLARE
  partner RECORD;
BEGIN
  FOR partner IN SELECT id FROM public.white_label_partners LOOP
    PERFORM public.seed_resend_kb_articles(partner.id);
  END LOOP;
END;
$$;
