
-- 1. Alter profiles table
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS onboarding_completed boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS onboarding_completed_at timestamptz;

-- 2. Alter platform_knowledge table
ALTER TABLE public.platform_knowledge
ADD COLUMN IF NOT EXISTS content_type text NOT NULL DEFAULT 'feature',
ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS onboarding_step integer;

-- 3. Alter wl_knowledge_base table
ALTER TABLE public.wl_knowledge_base
ADD COLUMN IF NOT EXISTS content_type text NOT NULL DEFAULT 'article',
ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS onboarding_step integer,
ADD COLUMN IF NOT EXISTS audience text NOT NULL DEFAULT 'client';

-- 4. Seed comprehensive knowledge base entries across all 10 dashboards
-- Clear existing thin entries and replace with rich content
DELETE FROM public.platform_knowledge;

-- ===== ADMIN DASHBOARD =====
INSERT INTO public.platform_knowledge (dashboard, title, description, content_type, sort_order, is_active) VALUES
-- Features
('admin', 'Dashboard Overview', 'The admin overview page at **Dashboard** shows real-time stats: total leads, clients, agents, calls, WL partners, open tickets, and WL revenue. It includes workflow alerts for stuck billing, unverified WL clients, and payment failures. Quick action buttons link to all major sections.', 'feature', 1, true),
('admin', 'Lead Management', 'Navigate to **Leads** in the sidebar to view, filter, and manage all leads. Each lead shows name, email, source, status, pipeline stage, and score. Click any lead to see full details including contact info, billing setup, call logs, and activity timeline. Use the pipeline stage dropdown to move leads through the funnel.', 'feature', 2, true),
('admin', 'Client Management', 'Navigate to **Clients** to see all active clients with their service type, plan details, and billing status. Click a client to view their scripts, call logs, agent assignments, and billing configuration. You can edit client details, manage add-ons, and update forwarding numbers.', 'feature', 3, true),
('admin', 'CRM & Activities', 'Navigate to **CRM** to manage the full customer relationship pipeline. Track activities, follow-ups, meetings, and communications for each lead. Use task management to assign and track work across the sales team.', 'feature', 4, true),
('admin', 'Agent Management', 'Navigate to **Agents** to view all agents, their skills, shift status, and assigned clients. You can manage agent roles, review performance, and handle onboarding status.', 'feature', 5, true),
('admin', 'Partner Management', 'Navigate to **Partners** to manage affiliates and white-label partners. The White Label tab shows all WL partners with status, client count, and monthly minutes. Click "Manage" on any partner to access their full detail page with pricing, clients, campaign mappings, and usage.', 'feature', 6, true),
('admin', 'Ticket System', 'Navigate to **Tickets** to see support tickets across all portals (client, sales, billing, tech, HR, WL). Filter by status, source, priority, and assignee. Each ticket shows full conversation thread with internal notes capability.', 'feature', 7, true),
('admin', 'Billing Administration', 'Navigate to **Billing** to manage subscriptions, invoices, payment methods, and custom plans. View payment failure alerts and Stripe integration status. Generate invoices and send payment links.', 'feature', 8, true),
('admin', 'Analytics & Reports', 'Navigate to **Analytics** to view comprehensive dashboards: lead conversion funnels, call volume trends, revenue breakdowns, agent performance metrics, and WL partner revenue charts. Export data for external reporting.', 'feature', 9, true),
('admin', 'User Management', 'Navigate to **Users** to manage all platform users, assign roles (admin, client, agent, supervisor, sales, billing, tech, HR, affiliate, white_label), and control access permissions across dashboards.', 'feature', 10, true),
('admin', 'Blog Management', 'Navigate to **Blog** to create, edit, and publish blog posts. Manage categories, tags, SEO metadata, and featured images. Use the auto-blog queue for AI-generated content. Track keyword rankings in the Keywords section.', 'feature', 11, true),
('admin', 'Outbound Calls', 'Navigate to **Outbound Calls** to view and manage outbound call requests from clients. Track call status, assign agents, and monitor completion.', 'feature', 12, true),
('admin', 'Settings', 'Navigate to **Settings** to configure platform-wide settings including company info, notification preferences, and integration configurations.', 'feature', 13, true),
-- Procedures
('admin', 'How to onboard a new client', 'To onboard a new client: 1) Navigate to **Leads** and find the lead. 2) Click the lead to open their detail page. 3) Update the pipeline stage to "ready_for_billing" — this automatically notifies the billing team. 4) Once billing sets up payment, move to "active" — this notifies supervisors and assigned agents. 5) Navigate to **Clients** to verify the client appears with correct service type and plan. 6) Assign agents via the client detail page.', 'procedure', 1, true),
('admin', 'How to manage a WL partner', 'To manage a white-label partner: 1) Navigate to **Partners** > **White Label** tab. 2) Click "Manage" on the partner row to open their detail page. 3) Use the tabs to configure wholesale pricing, verify client billing, map Five9 campaigns, view usage, and manage agreements. 4) Changes to pricing are reflected in the partner''s portal immediately.', 'procedure', 2, true),
('admin', 'How to handle escalated tickets', 'To handle escalated tickets: 1) Navigate to **Tickets** and filter by status "escalated". 2) Review the full conversation thread and any internal notes. 3) Reassign to the appropriate department using the "Transfer" action. 4) Add an internal note with resolution steps. 5) Update status to "in_progress" or "resolved".', 'procedure', 3, true),
('admin', 'How to assign user roles', 'To assign roles: 1) Navigate to **Users** in the sidebar. 2) Find the user by name or email. 3) Click "Manage Roles" to add or remove roles. 4) Available roles: admin, client, agent, supervisor, sales, billing, tech, hr, affiliate, white_label. 5) Users can have multiple roles and will see navigation for each assigned dashboard.', 'procedure', 4, true),
('admin', 'How to create a custom billing plan', 'To create a custom plan: 1) Navigate to **Billing** > custom plans section. 2) Click "Create Custom Plan". 3) Set plan type (per-minute or fixed), rates, and minimum monthly charge. 4) Assign to a specific client from the lead detail page. 5) The billing team can activate the plan and create the corresponding Stripe subscription.', 'procedure', 5, true),
('admin', 'How to view analytics', 'To view analytics: 1) Navigate to **Analytics** in the sidebar. 2) Use date range filters to select the reporting period. 3) View lead funnel, call volumes, revenue charts, and agent metrics. 4) The Partner Revenue section shows WL wholesale revenue trends and per-partner breakdowns.', 'procedure', 6, true),
-- Onboarding
('admin', 'Welcome to Admin Dashboard', 'Welcome to the Admin Command Center! This dashboard gives you complete control over every aspect of the platform. Let''s walk through the key areas you''ll use daily.', 'onboarding', 0, true),
('admin', 'Your Dashboard Overview', 'Your home page shows real-time stats across all operations. Navigate to **Dashboard** to see leads, clients, agents, calls, partners, and tickets at a glance. Workflow alerts will flag items needing your attention — like stuck billing or unverified WL clients.', 'onboarding', 1, true),
('admin', 'Managing Leads & Pipeline', 'Navigate to **Leads** to see your entire sales pipeline. Each lead progresses through stages: new → contacted → qualified → proposal → ready_for_billing → active. Moving a lead to "ready_for_billing" automatically notifies the billing team.', 'onboarding', 2, true),
('admin', 'Client Operations', 'Navigate to **Clients** to manage active accounts. Each client has scripts, call logs, agent assignments, and billing details. Navigate to **Outbound Calls** to handle client call-back requests.', 'onboarding', 3, true),
('admin', 'Team & Agent Management', 'Navigate to **Agents** to see your team. Navigate to **Users** to assign roles across the platform. Each role unlocks a different dashboard — agent, supervisor, sales, billing, tech, HR, and more.', 'onboarding', 4, true),
('admin', 'Partner Ecosystem', 'Navigate to **Partners** to manage affiliates and white-label partners. WL partners get their own isolated portal with branding, clients, and billing — all configured from the partner detail page.', 'onboarding', 5, true),
('admin', 'Support & Tickets', 'Navigate to **Tickets** to see all support requests across every portal. Tickets are auto-routed by source department. You can reassign, escalate, or transfer tickets between departments.', 'onboarding', 6, true),
('admin', 'Analytics & Growth', 'Navigate to **Analytics** for comprehensive reporting. Track lead conversion rates, call volumes, revenue trends, agent performance, and WL partner growth. Use these insights to optimize operations.', 'onboarding', 7, true),

-- ===== CLIENT DASHBOARD =====
('client', 'Dashboard Overview', 'Your client dashboard at **Dashboard** shows your account summary: recent calls, upcoming scheduled callbacks, active scripts, and billing status. Quick stats give you a snapshot of your service usage.', 'feature', 1, true),
('client', 'Call Logs', 'Navigate to **Call Logs** to view all incoming and outgoing calls. Each log shows date, time, caller info, duration, disposition, and agent name. Use filters to search by date range, call type, or agent. Export call data as CSV for your records.', 'feature', 2, true),
('client', 'Scripts Management', 'Navigate to **Scripts** to view and manage your call handling scripts. Each script includes greeting text, call handling rules, and FAQs. Request changes by submitting an edit which goes to the supervisor team for review.', 'feature', 3, true),
('client', 'Schedule', 'Navigate to **Schedule** to view and manage your on-call schedule. Set business hours, after-hours handling, holiday schedules, and special date overrides. Changes take effect immediately.', 'feature', 4, true),
('client', 'Billing & Invoices', 'Navigate to **Billing** to view your subscription plan, usage for the current period, invoices, and payment method. Update your card on file or view past invoices. Usage shows minutes consumed vs your plan allocation.', 'feature', 5, true),
('client', 'Support', 'Navigate to **Support** to ask questions using the AI assistant or submit support tickets. The AI assistant can answer how-to questions instantly. For complex issues, submit a ticket and track its progress.', 'feature', 6, true),
('client', 'Referrals', 'Navigate to **Referrals** to share your referral link and earn credits. Track referred contacts and see your earned rewards. Referral bonuses are applied as account credits.', 'feature', 7, true),
('client', 'Outbound Call Requests', 'Navigate to **Outbound Requests** to request callback services. Enter the contact name, phone, and reason. Mark urgency level. Agents are notified automatically and will complete the call on your behalf.', 'feature', 8, true),
('client', 'Settings', 'Navigate to **Settings** to update your profile information, notification preferences, and account details.', 'feature', 9, true),
-- Procedures
('client', 'How to view my call logs', 'To view call logs: 1) Navigate to **Call Logs** in the sidebar. 2) Use date filters to select a date range. 3) Filter by call direction (inbound/outbound) or disposition. 4) Click any call row to see full details including notes and recording status.', 'procedure', 1, true),
('client', 'How to change my call handling script', 'To change your script: 1) Navigate to **Scripts** in the sidebar. 2) Click on the active script to view it. 3) Click "Request Edit" to submit your changes. 4) A supervisor will review and approve the changes. 5) You''ll be notified once the updated script is live.', 'procedure', 2, true),
('client', 'How to manage my on-call schedule', 'To manage your schedule: 1) Navigate to **Schedule** in the sidebar. 2) Set your regular business hours using the weekly grid. 3) Add holiday dates or special overrides. 4) Configure after-hours handling (voicemail, forwarding, or live answering). 5) Save changes — they take effect immediately.', 'procedure', 3, true),
('client', 'How to submit a support ticket', 'To submit a ticket: 1) Navigate to **Support** in the sidebar. 2) Click the "Support Tickets" tab. 3) Click "Submit Ticket". 4) Fill in the title, description, and priority. 5) Submit and track your ticket''s progress in the ticket list.', 'procedure', 4, true),
('client', 'How to request an outbound call', 'To request an outbound call: 1) Navigate to **Outbound Requests** in the sidebar. 2) Click "New Request". 3) Enter the contact''s name and phone number. 4) Add the reason and set urgency (normal or urgent). 5) Submit — agents will be notified and complete the call.', 'procedure', 5, true),
-- Onboarding
('client', 'Welcome to Your Dashboard', 'Welcome! This dashboard is your command center for managing your answering service. Let''s walk through the key features you''ll use.', 'onboarding', 0, true),
('client', 'Viewing Your Calls', 'Navigate to **Call Logs** to see every call handled on your behalf. You''ll find caller details, duration, and how each call was resolved. Use date filters to find specific calls.', 'onboarding', 1, true),
('client', 'Your Call Scripts', 'Navigate to **Scripts** to see how our agents answer your calls. Your script includes your greeting, FAQs, and call handling rules. You can request changes anytime.', 'onboarding', 2, true),
('client', 'Managing Your Schedule', 'Navigate to **Schedule** to set when and how calls are handled. Set business hours, after-hours rules, and holiday schedules. Changes take effect immediately.', 'onboarding', 3, true),
('client', 'Billing & Usage', 'Navigate to **Billing** to track your usage and manage payments. See minutes used vs your plan, view invoices, and update payment methods.', 'onboarding', 4, true),
('client', 'Getting Help', 'Navigate to **Support** anytime you need assistance. Our AI assistant can answer most questions instantly. For anything else, submit a support ticket and we''ll get back to you promptly.', 'onboarding', 5, true),

-- ===== AGENT DASHBOARD =====
('agent', 'Dashboard Overview', 'Your agent dashboard shows your current shift status, assigned clients, recent calls, upcoming schedule, and open tasks. Clock in/out controls are prominently displayed at the top.', 'feature', 1, true),
('agent', 'Clock In/Out', 'Use the clock in/out button on your **Dashboard** to start and end shifts. While clocked in, your break timer and shift duration are tracked. Breaks can be started/stopped from the shift panel. Your supervisor reviews all shift times.', 'feature', 2, true),
('agent', 'Client Scripts', 'Navigate to **Scripts** to view call handling scripts for all your assigned clients. Each script shows the greeting, FAQ responses, call handling rules, and escalation procedures. Always review the script before taking calls for a client.', 'feature', 3, true),
('agent', 'Call Logs', 'Navigate to **Call Logs** to view calls you''ve handled. Filter by client, date, or disposition. Add notes to calls after completion. Your call metrics contribute to your performance reviews.', 'feature', 4, true),
('agent', 'Tasks', 'Navigate to **Tasks** to see work assigned to you by supervisors. Tasks include follow-up calls, documentation, training items, and administrative work. Mark tasks complete when finished.', 'feature', 5, true),
('agent', 'Schedule', 'Navigate to **Schedule** to view your upcoming shifts, request time off, and claim open shifts. Your schedule is managed by supervisors but you can view it anytime and request changes.', 'feature', 6, true),
('agent', 'Shifts & Timekeeping', 'Navigate to **Shifts** to see your shift history with clock-in/out times, break durations, and total hours. If a supervisor edits your shift, you''ll receive a notification with the reason.', 'feature', 7, true),
('agent', 'Outbound Calls', 'Navigate to **Outbound Calls** to see call requests from clients. Claim a request, make the call, and log the outcome. Urgent requests are highlighted and should be prioritized.', 'feature', 8, true),
('agent', 'Messages', 'Navigate to **Messages** to communicate with supervisors and team members. Messages are organized by conversation thread.', 'feature', 9, true),
('agent', 'Time Off', 'Navigate to **Time Off** to request vacation, sick days, or personal time. Submit requests with dates and reason. Your supervisor will approve or deny with notification.', 'feature', 10, true),
('agent', 'My Profile', 'Navigate to **My Profile** to update your personal information, skills, and availability preferences.', 'feature', 11, true),
-- Procedures
('agent', 'How to clock in and out', 'To clock in: 1) Navigate to your **Dashboard**. 2) Click the "Clock In" button at the top. 3) Your shift timer starts immediately. 4) To take a break, click "Start Break" and select break type. 5) Click "End Break" when returning. 6) At shift end, click "Clock Out". 7) Your supervisor reviews and approves shift times.', 'procedure', 1, true),
('agent', 'How to view my client scripts', 'To view scripts: 1) Navigate to **Scripts** in the sidebar. 2) Select a client from the list. 3) Review the greeting, FAQ, and call handling rules. 4) Use the search function to quickly find specific information during calls.', 'procedure', 2, true),
('agent', 'How to submit a shift invoice', 'Shift invoices are generated automatically from your approved shifts. Navigate to **Shifts** to see your approved shift history. If you notice discrepancies, contact your supervisor or submit a support ticket.', 'procedure', 3, true),
('agent', 'How to log outbound calls', 'To handle outbound calls: 1) Navigate to **Outbound Calls** in the sidebar. 2) Review available call requests. 3) Click "Claim" on a request. 4) Make the call and record the outcome. 5) Add notes about the conversation. 6) Mark the request as completed.', 'procedure', 4, true),
('agent', 'How to request time off', 'To request time off: 1) Navigate to **Time Off** in the sidebar. 2) Click "Request Time Off". 3) Select the type (vacation, sick, personal). 4) Choose start and end dates. 5) Add a reason. 6) Submit — your supervisor will be notified and will approve or deny.', 'procedure', 5, true),
('agent', 'How to manage assigned tasks', 'To manage tasks: 1) Navigate to **Tasks** in the sidebar. 2) View tasks sorted by priority and due date. 3) Click a task to see full details. 4) When complete, click "Mark Complete". 5) Your supervisor receives notification of completion.', 'procedure', 6, true),
-- Onboarding
('agent', 'Welcome Agent!', 'Welcome to your Agent Dashboard! This is your workspace for handling calls, managing shifts, and staying connected with your team. Let''s get you set up.', 'onboarding', 0, true),
('agent', 'Clocking In', 'Your first step each day: Navigate to **Dashboard** and click "Clock In" to start your shift. Your shift timer, break controls, and status are all managed from here.', 'onboarding', 1, true),
('agent', 'Your Client Scripts', 'Navigate to **Scripts** to see the call handling scripts for your assigned clients. Always review scripts before taking calls — they contain greetings, FAQs, and escalation rules.', 'onboarding', 2, true),
('agent', 'Handling Calls', 'Navigate to **Call Logs** to view and log calls. After each call, add notes and set the disposition. Outbound call requests are found in **Outbound Calls**.', 'onboarding', 3, true),
('agent', 'Your Schedule & Shifts', 'Navigate to **Schedule** to see upcoming shifts and **Shifts** to review your shift history. Request time off through **Time Off** in the sidebar.', 'onboarding', 4, true),
('agent', 'Tasks & Communication', 'Navigate to **Tasks** for assigned work items and **Messages** to communicate with your supervisor. Complete tasks promptly and check messages regularly.', 'onboarding', 5, true),
('agent', 'Your Profile', 'Navigate to **My Profile** to update your information and skills. Navigate to **Support** if you need help with anything. The AI assistant can answer most questions instantly.', 'onboarding', 6, true),

-- ===== SUPERVISOR DASHBOARD =====
('supervisor', 'Dashboard Overview', 'Your supervisor dashboard shows team status: agents currently clocked in, pending shift approvals, open tasks, and recent activity. Quick stats summarize team performance.', 'feature', 1, true),
('supervisor', 'Agent Management', 'Navigate to **Agents** to see all agents under your supervision. View their status, skills, assigned clients, and performance metrics. Click any agent for detailed management.', 'feature', 2, true),
('supervisor', 'Schedule Management', 'Navigate to **Schedule** to create and manage agent schedules. Set shifts with recurring patterns, handle open shift postings, and process time-off requests. Agents are notified of schedule changes.', 'feature', 3, true),
('supervisor', 'Shift Reviews', 'Navigate to **Shift Reviews** to approve or edit agent shift times. View clock-in/out records, break durations, and flagged discrepancies. Edit shifts with a required reason — agents are notified.', 'feature', 4, true),
('supervisor', 'Task Management', 'Navigate to **Tasks** to create, assign, and track tasks for your agents. Set priorities, due dates, and descriptions. Monitor task completion rates across your team.', 'feature', 5, true),
('supervisor', 'Script Reviews', 'Navigate to **Script Reviews** to review and approve client script change requests. Compare current vs proposed changes and approve or request modifications.', 'feature', 6, true),
('supervisor', 'Agent Onboarding', 'Navigate to **Agent Onboarding** to manage the onboarding pipeline for new agents. Track progress through each step from offer to live training to final activation.', 'feature', 7, true),
('supervisor', 'Client Assignments', 'Navigate to **Client Assignments** to manage which agents handle which clients. Set primary agents and configure skill-based routing.', 'feature', 8, true),
('supervisor', 'Performance Reviews', 'Navigate to **Performance** to conduct and view agent performance reviews. Score quality, communication, attendance, and overall performance for review periods.', 'feature', 9, true),
('supervisor', 'Outbound Calls', 'Navigate to **Outbound Calls** to monitor and manage outbound call queues. See all client requests, assign agents, and track completion.', 'feature', 10, true),
('supervisor', 'Escalations', 'Navigate to **Escalations** to handle escalated issues from agents or clients. Prioritize and resolve critical items.', 'feature', 11, true),
-- Procedures
('supervisor', 'How to approve agent shifts', 'To approve shifts: 1) Navigate to **Shift Reviews** in the sidebar. 2) Review pending shifts showing clock-in/out times and breaks. 3) Click "Approve" to accept or "Edit" to modify times. 4) If editing, provide a reason — the agent will be notified. 5) Approved shifts feed into payroll calculations.', 'procedure', 1, true),
('supervisor', 'How to manage agents', 'To manage your team: 1) Navigate to **Agents** in the sidebar. 2) View each agent''s current status, assigned clients, and skills. 3) Click an agent to see their full profile, shift history, and performance data. 4) Use bulk actions for schedule changes or client reassignments.', 'procedure', 2, true),
('supervisor', 'How to manage the team schedule', 'To manage schedules: 1) Navigate to **Schedule** in the sidebar. 2) Use the calendar view to see all agent shifts. 3) Click any slot to create a new shift. 4) Set recurrence (daily, weekly) for regular schedules. 5) Post open shifts when coverage is needed — qualified agents are notified. 6) Process time-off requests from the pending queue.', 'procedure', 3, true),
('supervisor', 'How to review client scripts', 'To review scripts: 1) Navigate to **Script Reviews** in the sidebar. 2) Review pending change requests from clients. 3) Compare the current script with proposed changes. 4) Approve, reject, or request modifications. 5) Approved changes go live immediately.', 'procedure', 4, true),
('supervisor', 'How to onboard a new agent', 'To onboard an agent: 1) Navigate to **Agent Onboarding** in the sidebar. 2) Review the onboarding pipeline. 3) Each step alternates between supervisor actions (system setup, training) and applicant actions (documents, self-training). 4) Complete your assigned steps and monitor applicant progress. 5) The final step activates the agent account.', 'procedure', 5, true),
-- Onboarding
('supervisor', 'Welcome Supervisor!', 'Welcome to the Supervisor Dashboard! You''ll manage agents, schedules, scripts, and team performance from here. Let''s tour the key areas.', 'onboarding', 0, true),
('supervisor', 'Your Team', 'Navigate to **Agents** to see your team roster. Each agent shows their status, skills, and current assignment. This is your go-to page for team oversight.', 'onboarding', 1, true),
('supervisor', 'Scheduling', 'Navigate to **Schedule** to create and manage shifts. Navigate to **Shift Reviews** to approve agent clock-in/out times. These are daily tasks you''ll use frequently.', 'onboarding', 2, true),
('supervisor', 'Scripts & Quality', 'Navigate to **Script Reviews** for client script changes and **Performance** for agent reviews. Quality control is central to your role.', 'onboarding', 3, true),
('supervisor', 'Tasks & Escalations', 'Navigate to **Tasks** to assign work and **Escalations** to handle critical issues. Navigate to **Outbound Calls** to manage call queues.', 'onboarding', 4, true),
('supervisor', 'Agent Onboarding', 'Navigate to **Agent Onboarding** when new team members join. The pipeline guides both you and the agent through every step from offer to activation.', 'onboarding', 5, true),
('supervisor', 'Support & Communication', 'Navigate to **Messages** for team communication and **Tickets** for support requests. Navigate to **Support** for the AI assistant if you need help with any feature.', 'onboarding', 6, true),

-- ===== SALES DASHBOARD =====
('sales', 'Dashboard Overview', 'Your sales dashboard shows your personal pipeline: leads by stage, upcoming meetings, recent activity, and monthly performance. Quick stats show conversion rates and revenue targets.', 'feature', 1, true),
('sales', 'Lead Management', 'Navigate to **Leads** to view and manage your assigned leads. Filter by stage, temperature, or date. Click any lead for the full detail view with contact info, notes, and activity history.', 'feature', 2, true),
('sales', 'Pipeline View', 'Navigate to **Pipeline** for a Kanban-style view of your leads across pipeline stages. Drag leads between stages to update their progress. See deal values and conversion predictions.', 'feature', 3, true),
('sales', 'Meetings', 'Navigate to **Meetings** to view scheduled demos, consultations, and follow-ups. Meetings are synced with lead records. Add meeting notes and outcomes after each session.', 'feature', 4, true),
('sales', 'Proposals', 'Navigate to **Proposals** to create and track sales proposals. Generate professional proposals with pricing, service details, and terms. Track proposal status (sent, viewed, accepted, declined).', 'feature', 5, true),
('sales', 'Performance', 'Navigate to **Performance** to see your sales metrics: conversion rates, revenue generated, commissions earned, and activity trends. Compare against targets and team averages.', 'feature', 6, true),
-- Procedures
('sales', 'How to manage leads', 'To manage leads: 1) Navigate to **Leads** in the sidebar. 2) Review your assigned leads sorted by score and temperature. 3) Click a lead to open their detail page. 4) Log activities (calls, emails) using the activity timeline. 5) Update the pipeline stage as you progress the deal. 6) When ready, move to "ready_for_billing" to hand off to the billing team.', 'procedure', 1, true),
('sales', 'How to track pipeline', 'To track your pipeline: 1) Navigate to **Pipeline** in the sidebar. 2) View leads in Kanban columns by stage. 3) Drag leads between stages to update progress. 4) Click any lead card for quick details. 5) Use the pipeline summary at the top for conversion metrics.', 'procedure', 2, true),
('sales', 'How to schedule meetings', 'To schedule meetings: 1) Navigate to **Meetings** in the sidebar. 2) Click "Schedule Meeting". 3) Select the lead, meeting type, date/time, and location. 4) Add meeting notes before or after. 5) Update the meeting outcome when complete.', 'procedure', 3, true),
-- Onboarding
('sales', 'Welcome to Sales!', 'Welcome to the Sales Dashboard! This is your command center for managing leads, tracking your pipeline, and closing deals. Let''s get you oriented.', 'onboarding', 0, true),
('sales', 'Your Lead Pipeline', 'Navigate to **Leads** to see all your assigned leads. Navigate to **Pipeline** for a visual Kanban view. Moving leads through stages triggers automated actions — like notifying billing when a deal is ready.', 'onboarding', 1, true),
('sales', 'Meetings & Follow-ups', 'Navigate to **Meetings** to schedule and track your sales calls. Each meeting links to the lead record so all activity is tracked in one place.', 'onboarding', 2, true),
('sales', 'Performance & Commissions', 'Navigate to **Performance** to track your conversion rates and commissions. When a lead moves to "ready_for_billing", your commission is automatically calculated.', 'onboarding', 3, true),
('sales', 'Getting Help', 'Navigate to **Support** for the AI assistant. Navigate to **Tickets** to submit support requests. Your support history is tracked in the ticket system.', 'onboarding', 4, true),

-- ===== BILLING DASHBOARD =====
('billing', 'Dashboard Overview', 'Your billing dashboard shows key metrics: active subscriptions, monthly recurring revenue, pending invoices, payment failures, and agent payouts due. Quick action cards link to common tasks.', 'feature', 1, true),
('billing', 'Client Lookup', 'Navigate to **Client Lookup** to search for any client by name, email, or account code. View their subscription status, payment history, usage, and billing configuration. Process refunds, send payment links, or update plans from here.', 'feature', 2, true),
('billing', 'Subscriptions', 'Navigate to **Subscriptions** to manage all active Stripe subscriptions. View plan details, usage meters, add-ons, and billing cycles. Cancel, pause, or modify subscriptions.', 'feature', 3, true),
('billing', 'Payment Issues', 'Navigate to **Payment Issues** to see all failed payments and overdue accounts. Send card update links, retry charges, or escalate issues. Priority is given to accounts with multiple failures.', 'feature', 4, true),
('billing', 'Invoices & Payouts', 'Navigate to **Invoices** to manage agent payouts and client invoices. Review submitted invoices, approve payouts, and process payments through the integrated payment system.', 'feature', 5, true),
('billing', 'Commissions', 'Navigate to **Commissions** to manage sales commissions. Review pending commissions triggered by lead conversions and approve payments.', 'feature', 6, true),
('billing', 'WL Partners', 'Navigate to **WL Partners** to manage white-label partner billing. Verify client service configurations, trigger usage calculations, and review partner billing summaries.', 'feature', 7, true),
-- Procedures
('billing', 'How to process invoices', 'To process invoices: 1) Navigate to **Invoices** in the sidebar. 2) Review pending invoices from agents or auto-generated client invoices. 3) Verify amounts and details. 4) Approve for payment processing. 5) Track payment status through completion.', 'procedure', 1, true),
('billing', 'How to handle payment failures', 'To handle payment failures: 1) Navigate to **Payment Issues** in the sidebar. 2) Review failed payment details (amount, failure reason, attempt count). 3) Click "Send Card Update Link" to request updated payment info from the client. 4) Or click "Retry Charge" to attempt the charge again. 5) For chronic failures, escalate by contacting the client directly.', 'procedure', 2, true),
('billing', 'How to process agent payouts', 'To process payouts: 1) Navigate to **Invoices** > Agent Payouts section. 2) Review approved shifts and calculated amounts. 3) Verify banking details are on file. 4) Approve the payout batch. 5) Payouts are processed through the configured payment provider.', 'procedure', 3, true),
('billing', 'How to verify WL client billing', 'To verify WL client billing: 1) Navigate to **WL Partners** in the sidebar. 2) Find the partner with unverified clients. 3) Review each client''s service configuration (service type, language, campaigns). 4) Click the verify toggle to confirm. 5) The WL partner receives notification of verification status changes.', 'procedure', 4, true),
-- Onboarding
('billing', 'Welcome to Billing!', 'Welcome to the Billing Dashboard! You manage subscriptions, payments, invoices, and partner billing from here. Let''s walk through the essentials.', 'onboarding', 0, true),
('billing', 'Client Billing', 'Navigate to **Client Lookup** to find any client''s billing details. Navigate to **Subscriptions** to manage active plans. Navigate to **Payment Issues** for failed charges.', 'onboarding', 1, true),
('billing', 'Invoices & Payouts', 'Navigate to **Invoices** to manage both client invoices and agent payouts. Navigate to **Commissions** for sales commission management.', 'onboarding', 2, true),
('billing', 'WL Partner Billing', 'Navigate to **WL Partners** to manage white-label partner billing. Verify client configs, trigger usage calculations, and review billing summaries.', 'onboarding', 3, true),
('billing', 'Getting Help', 'Navigate to **Support** for the AI assistant. Navigate to **Tickets** to submit or view support requests.', 'onboarding', 4, true),

-- ===== TECH DASHBOARD =====
('tech', 'Dashboard Overview', 'Your tech dashboard shows system health: open tickets, system issues, and knowledge base stats. Quick links to common tech tasks.', 'feature', 1, true),
('tech', 'Ticket Management', 'Navigate to **Tickets** to manage technical support tickets. Filter by priority, status, and category. Respond to tickets with technical solutions and track resolution.', 'feature', 2, true),
('tech', 'System Issues', 'Navigate to **System Issues** to log and track platform bugs, outages, and performance problems. Create issue reports, assign severity, and track through resolution.', 'feature', 3, true),
('tech', 'Knowledge Base Management', 'Navigate to **Knowledge Base** to manage the platform-wide knowledge base. Add, edit, and organize entries that power the PiP AI assistant across all dashboards. Control content type, dashboard scope, and onboarding sequences.', 'feature', 4, true),
-- Procedures
('tech', 'How to manage knowledge base entries', 'To manage knowledge base: 1) Navigate to **Knowledge Base** in the sidebar. 2) Filter by dashboard and content type. 3) Click "Add Entry" to create new knowledge. 4) Set the dashboard, content type (feature/procedure/onboarding/faq), and description. 5) For onboarding entries, set the step number. 6) Toggle active/inactive to control visibility. 7) Changes affect PiP''s responses immediately.', 'procedure', 1, true),
('tech', 'How to handle system issues', 'To log system issues: 1) Navigate to **System Issues** in the sidebar. 2) Click "Report Issue". 3) Set severity (critical, high, medium, low). 4) Describe the issue with steps to reproduce. 5) Assign to a team member. 6) Track through investigation → fix → verification → resolved.', 'procedure', 2, true),
-- Onboarding
('tech', 'Welcome to Tech Support!', 'Welcome to the Tech Dashboard! You manage system health, support tickets, and the platform knowledge base. Let''s get oriented.', 'onboarding', 0, true),
('tech', 'Tickets & Issues', 'Navigate to **Tickets** for support requests and **System Issues** for platform bugs. These are your primary daily workspaces.', 'onboarding', 1, true),
('tech', 'Knowledge Base', 'Navigate to **Knowledge Base** to manage content that powers the AI assistant (PiP) across all dashboards. Rich, detailed entries = better AI answers for everyone.', 'onboarding', 2, true),
('tech', 'Getting Help', 'Navigate to **Support** for the AI assistant if you need guidance on any tech portal feature.', 'onboarding', 3, true),

-- ===== HR DASHBOARD =====
('hr', 'Dashboard Overview', 'Your HR dashboard shows workforce metrics: total employees, active onboardings, pending time-off requests, upcoming payroll, and recent communications. Quick stats keep you informed.', 'feature', 1, true),
('hr', 'Employee Directory', 'Navigate to **Directory** to view all employees with their roles, departments, status, and contact info. Search and filter to find specific team members. Click any employee for their full profile.', 'feature', 2, true),
('hr', 'Onboarding Management', 'Navigate to **Onboarding** to manage new hire pipelines. Each onboarding has a 10-step process: offer → acceptance → contract signing → banking details → system provisioning → training → HR approval → activation. Track progress across all active onboardings.', 'feature', 3, true),
('hr', 'Offboarding', 'Navigate to **Offboarding** to manage employee departures. Track equipment return, access revocation, final pay, and exit documentation through a structured offboarding checklist.', 'feature', 4, true),
('hr', 'Payroll', 'Navigate to **Payroll** to review and process payroll. View approved shifts, calculated hours, pay rates, and deductions. Generate payroll summaries and export for processing.', 'feature', 5, true),
('hr', 'Time Off Management', 'Navigate to **Time Off** to manage all time-off requests. Approve, deny, or request more information. View team calendars to check coverage before approving. Sick days trigger urgent notifications to supervisors.', 'feature', 6, true),
('hr', 'Job Postings', 'Navigate to **Jobs** to create and manage job postings. Set title, department, description, and requirements. Track applications and move candidates through the hiring pipeline.', 'feature', 7, true),
('hr', 'Contracts', 'Navigate to **Contracts** to manage employment contracts. Create, send, and track contract signing status. Store signed contracts for compliance.', 'feature', 8, true),
('hr', 'Communications', 'Navigate to **Communications** to send announcements and messages to all staff or specific groups. Track read receipts and manage communication categories.', 'feature', 9, true),
('hr', 'Tickets', 'Navigate to **Tickets** to manage HR-specific support requests from staff. Handle questions about benefits, policies, and employment matters.', 'feature', 10, true),
-- Procedures
('hr', 'How to onboard a new hire', 'To onboard a new hire: 1) Navigate to **Onboarding** in the sidebar. 2) Click **Send Offer** to create an offer package with role, pay rate, and start date. 3) The applicant receives an email with a link to their Applicant Portal where they accept, sign contracts, and submit banking details. 4) Once accepted, the onboarding moves through a 10-step pipeline visible in the **Pipeline** tab. 5) Steps alternate between supervisor actions (Google Workspace, Five9 provisioning) and applicant actions (self-training, banking). 6) HR gives final approval on the **HR Approval** step to mark onboarding complete. 7) The agent''s status automatically changes to active and they appear in the Agent Directory.', 'procedure', 1, true),
('hr', 'How to process payroll', 'To process payroll: 1) Navigate to **Payroll** in the sidebar. 2) Select the pay period. 3) Review approved shifts and calculated hours for each agent. 4) Verify pay rates and any deductions. 5) Generate the payroll summary. 6) Export the data for your payroll provider. 7) Mark the period as processed once payments are sent.', 'procedure', 2, true),
('hr', 'How to initiate offboarding', 'To initiate offboarding: 1) Navigate to **Offboarding** in the sidebar. 2) Click "Start Offboarding" and select the employee. 3) Set the last working day. 4) The offboarding checklist is auto-generated: access revocation, equipment return, final pay calculation, exit documentation. 5) Track each step through completion. 6) Supervisors are notified to handle client reassignments.', 'procedure', 3, true),
('hr', 'How to create an onboarding template', 'To create an onboarding template: 1) Navigate to **Onboarding** > **Templates** tab. 2) Click "Create Template". 3) Define the template name and steps. 4) Each step can be assigned to supervisor or applicant. 5) Set step descriptions and required actions. 6) Save — the template can be selected when starting new onboardings.', 'procedure', 4, true),
('hr', 'How to send an announcement', 'To send an announcement: 1) Navigate to **Communications** in the sidebar. 2) Click "New Announcement". 3) Set the subject and message. 4) Select the audience (all staff, specific departments). 5) Send — recipients see it in their notifications and the communications feed.', 'procedure', 5, true),
('hr', 'How to approve time-off', 'To approve time-off: 1) Navigate to **Time Off** in the sidebar. 2) Review pending requests showing dates, type, and reason. 3) Check the team calendar for coverage. 4) Click "Approve" or "Deny" with optional notes. 5) The agent receives a notification with your decision.', 'procedure', 6, true),
-- Onboarding
('hr', 'Welcome to HR Portal!', 'Welcome to the HR Portal! You manage the entire employee lifecycle from here — hiring, onboarding, payroll, time-off, and offboarding. Let''s tour the key areas.', 'onboarding', 0, true),
('hr', 'Employee Directory', 'Navigate to **Directory** to see all team members. This is your central roster with roles, status, and contact details for every employee.', 'onboarding', 1, true),
('hr', 'Onboarding Pipeline', 'Navigate to **Onboarding** for the most critical HR workflow. New hires go through a 10-step pipeline from offer to activation. You and supervisors share responsibility for completing steps.', 'onboarding', 2, true),
('hr', 'Payroll & Time-Off', 'Navigate to **Payroll** to process pay and **Time Off** to manage leave requests. These are your regular operational tasks.', 'onboarding', 3, true),
('hr', 'Jobs & Contracts', 'Navigate to **Jobs** to manage postings and **Contracts** for employment agreements. These drive your hiring pipeline.', 'onboarding', 4, true),
('hr', 'Communications & Support', 'Navigate to **Communications** to announce to staff and **Tickets** for HR support requests. Navigate to **Support** for AI-powered help.', 'onboarding', 5, true),

-- ===== AFFILIATE DASHBOARD =====
('affiliate', 'Dashboard Overview', 'Your affiliate dashboard shows your referral stats: total referrals, conversion rate, total earnings, and pending payouts. Your unique referral link is displayed prominently for easy sharing.', 'feature', 1, true),
('affiliate', 'Referrals', 'Navigate to **Referrals** to see all your referred contacts. Track each referral''s status (clicked, signed up, converted) and commission amount. See which referrals converted to paying clients.', 'feature', 2, true),
('affiliate', 'Performance', 'Navigate to **Performance** to view your referral analytics. Track trends over time, conversion rates, and earnings by month. Compare against tier thresholds for commission rate upgrades.', 'feature', 3, true),
('affiliate', 'Payouts', 'Navigate to **Payouts** to manage your earnings. Request payouts when your balance reaches the minimum threshold. Track payment history and set your preferred payment method.', 'feature', 4, true),
('affiliate', 'Marketing Assets', 'Navigate to **Marketing** to access banners, logos, and promotional materials. Download assets sized for social media, websites, and email campaigns. Use these to maximize your referral conversions.', 'feature', 5, true),
-- Procedures
('affiliate', 'How to get my referral link', 'Your unique referral link is displayed on your **Dashboard** at the top. Click the copy button to copy it. Share this link on your website, social media, or in emails. Anyone who signs up through your link is tracked as your referral.', 'procedure', 1, true),
('affiliate', 'How to view my earnings', 'To view earnings: 1) Navigate to **Performance** for a detailed breakdown by month. 2) Navigate to **Payouts** to see your available balance and payment history. 3) Your commission rate is based on your tier — visible on the Dashboard.', 'procedure', 2, true),
('affiliate', 'How to request a payout', 'To request a payout: 1) Navigate to **Payouts** in the sidebar. 2) Verify your payment method is set in **Settings**. 3) Click "Request Payout" when your balance meets the minimum threshold. 4) Payouts are processed within 5-7 business days.', 'procedure', 3, true),
-- Onboarding
('affiliate', 'Welcome Affiliate!', 'Welcome to the Affiliate Portal! You''ll earn commissions by referring new clients. Let''s get you set up for success.', 'onboarding', 0, true),
('affiliate', 'Your Referral Link', 'Your unique referral link is on your **Dashboard**. Copy it and share it anywhere — social media, your website, emails. Every signup through your link earns you a commission.', 'onboarding', 1, true),
('affiliate', 'Tracking & Earnings', 'Navigate to **Referrals** to track every referral. Navigate to **Performance** for analytics and trends. Your commission rate improves as you hit tier thresholds.', 'onboarding', 2, true),
('affiliate', 'Getting Paid', 'Navigate to **Payouts** to request withdrawals. Set your payment method in **Settings**. Navigate to **Marketing** for promotional materials to boost your referrals.', 'onboarding', 3, true),

-- ===== WHITE LABEL DASHBOARD =====
('white_label', 'Dashboard Overview', 'Your partner dashboard shows your business metrics: total clients, active clients, monthly minutes, usage costs, and recent activity. Quick links connect you to all management areas.', 'feature', 1, true),
('white_label', 'Client Management', 'Navigate to **Clients** to manage your clients. Add new clients with their service type, language support, and campaign details. View each client''s call volume and usage. Client configurations must be verified by the billing team before going live.', 'feature', 2, true),
('white_label', 'Branding', 'Navigate to **Branding** to configure your white-label portal appearance. Set your company name, logo, favicon, primary/secondary colors, and contact information. Your branding is applied to your client-facing portal.', 'feature', 3, true),
('white_label', 'Billing & Usage', 'Navigate to **Billing** for your subscription and payment details. Navigate to **Usage** for detailed usage breakdowns by client, campaign, and time period. Monthly usage drives your wholesale billing.', 'feature', 4, true),
('white_label', 'Campaign Management', 'Navigate to **Campaigns** to manage your Five9 campaign mappings. Each campaign maps calls to specific clients for accurate usage tracking and billing.', 'feature', 5, true),
('white_label', 'Knowledge Base', 'Navigate to **Knowledge Base** to create and manage articles for your clients. Your knowledge base is completely separate and branded — your clients never see the platform provider''s content.', 'feature', 6, true),
('white_label', 'Client Tickets', 'Navigate to **Client Tickets** to manage support requests from your clients. This is your own ticketing system — completely isolated from the platform''s internal ticketing.', 'feature', 7, true),
('white_label', 'Wholesale Pricing', 'Navigate to **Pricing** to view your wholesale rates. Pricing tiers are based on your tier level and volume. Volume discounts are applied automatically when you hit minute thresholds.', 'feature', 8, true),
('white_label', 'Agreements', 'Navigate to **Agreements** to view and sign partnership agreements. Current agreements show your negotiated terms and pricing snapshots.', 'feature', 9, true),
('white_label', 'Support', 'Navigate to **Support** to get help from your AI assistant or submit support tickets to the platform team. Your tickets are handled by dedicated partner support.', 'feature', 10, true),
-- Procedures
('white_label', 'How to set up branding', 'To set up branding: 1) Navigate to **Branding** in the sidebar. 2) Upload your company logo and favicon. 3) Set your company name and contact info. 4) Choose primary and secondary brand colors. 5) Preview how your portal will look to clients. 6) Save — changes apply to your client portal immediately.', 'procedure', 1, true),
('white_label', 'How to manage clients', 'To manage clients: 1) Navigate to **Clients** in the sidebar. 2) Click "Add Client" to create a new client. 3) Set service type (inbound, outbound, both), language support, and number of campaigns. 4) The billing team will verify your client''s configuration. 5) Once verified, the client goes live and calls are tracked.', 'procedure', 2, true),
('white_label', 'How to view billing', 'To view billing: 1) Navigate to **Billing** for your subscription status. 2) Navigate to **Usage** for detailed per-client usage. 3) Usage shows minutes by client and campaign for the current and past billing periods. 4) Your wholesale cost is calculated based on tier rates and surcharges.', 'procedure', 3, true),
('white_label', 'How to manage knowledge base', 'To manage your KB: 1) Navigate to **Knowledge Base** in the sidebar. 2) Click "New Article" to create content. 3) Set the audience (partner team or clients). 4) Write articles with how-to guides, FAQs, and procedures. 5) Your AI assistant uses these articles to help your clients.', 'procedure', 4, true),
-- Onboarding
('white_label', 'Welcome Partner!', 'Welcome to your Partner Dashboard! This is your command center for managing your white-label answering service business. Let''s tour the key areas.', 'onboarding', 0, true),
('white_label', 'Setting Up Your Brand', 'Navigate to **Branding** to make this portal yours. Upload your logo, set your company name and colors. Your clients will only ever see your brand — never ours.', 'onboarding', 1, true),
('white_label', 'Adding Clients', 'Navigate to **Clients** to add your first client. Set their service type, language, and campaign details. The billing team verifies each client before they go live.', 'onboarding', 2, true),
('white_label', 'Campaigns & Usage', 'Navigate to **Campaigns** to map Five9 campaigns to clients. Navigate to **Usage** to track minutes and costs. This drives your monthly wholesale billing.', 'onboarding', 3, true),
('white_label', 'Your Knowledge Base', 'Navigate to **Knowledge Base** to create articles for your clients. This content powers your branded AI assistant and client self-service.', 'onboarding', 4, true),
('white_label', 'Getting Support', 'Navigate to **Support** for AI-powered help or to submit tickets to our partner support team. We''re here to help you grow your business.', 'onboarding', 5, true);
